# Generated by Django 4.1 on 2022-09-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_getlat_reports_lat_rename_getlng_reports_lng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='hora',
        ),
        migrations.AddField(
            model_name='reports',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
